-- Run once using a migration role, never during Function startup.
CREATE SCHEMA IF NOT EXISTS fuel_app;
REVOKE ALL ON SCHEMA fuel_app FROM PUBLIC;
CREATE TABLE IF NOT EXISTS fuel_app.schema_migrations (
    version TEXT PRIMARY KEY, applied_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS fuel_app.vehicles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY CHECK (id BETWEEN 1 AND 9007199254740991),
    name TEXT NOT NULL CHECK (length(name) BETWEEN 1 AND 100),
    license_plate TEXT NOT NULL DEFAULT '',
    fuel_type TEXT NOT NULL DEFAULT 'E10 RON 95-III',
    price_zone SMALLINT NOT NULL DEFAULT 1 CHECK (price_zone IN (1,2)),
    city TEXT NOT NULL DEFAULT 'Đà Nẵng',
    tank_capacity_liters NUMERIC(8,3) NOT NULL DEFAULT 4 CHECK (tank_capacity_liters > 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS fuel_app.fuel_prices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY CHECK (id BETWEEN 1 AND 9007199254740991),
    fuel_type TEXT NOT NULL,
    price_zone SMALLINT NOT NULL CHECK (price_zone IN (1,2)),
    effective_at TIMESTAMPTZ NOT NULL,
    unit_price_vnd INTEGER NOT NULL CHECK (unit_price_vnd BETWEEN 1000 AND 100000),
    source TEXT NOT NULL CHECK (source IN ('manual','petrolimex')),
    source_url TEXT NOT NULL DEFAULT '', source_updated_at TIMESTAMPTZ,
    fetched_at TIMESTAMPTZ NOT NULL,
    UNIQUE(fuel_type, price_zone, effective_at, source)
);
CREATE TABLE IF NOT EXISTS fuel_app.fuel_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY CHECK (id BETWEEN 1 AND 9007199254740991),
    vehicle_id BIGINT NOT NULL REFERENCES fuel_app.vehicles(id) ON DELETE RESTRICT,
    filled_on DATE NOT NULL, filled_time TIME WITHOUT TIME ZONE,
    odometer_tenths BIGINT CHECK (odometer_tenths BETWEEN 0 AND 99999990),
    total_cost_vnd BIGINT NOT NULL CHECK (total_cost_vnd BETWEEN 1 AND 1000000000),
    unit_price_vnd_per_liter NUMERIC(20,6) NOT NULL CHECK (unit_price_vnd_per_liter > 0),
    volume_liters NUMERIC(20,6) NOT NULL CHECK (volume_liters > 0),
    volume_source TEXT NOT NULL DEFAULT 'calculated' CHECK (volume_source IN ('entered','calculated')),
    is_full_tank TEXT NOT NULL DEFAULT 'unknown' CHECK (is_full_tank IN ('yes','no','unknown')),
    notes TEXT NOT NULL DEFAULT '',
    price_id BIGINT REFERENCES fuel_app.fuel_prices(id) ON DELETE RESTRICT,
    price_source TEXT NOT NULL DEFAULT 'legacy' CHECK (price_source IN ('legacy','sample','manual','petrolimex')),
    fuel_type TEXT NOT NULL DEFAULT 'E10 RON 95-III',
    price_zone SMALLINT NOT NULL DEFAULT 1 CHECK (price_zone IN (1,2)),
    odo_source TEXT NOT NULL DEFAULT 'manual' CHECK (odo_source IN ('manual','photo_confirmed')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS fuel_app.metadata (key TEXT PRIMARY KEY, value TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS fuel_app.app_locks (
    name TEXT PRIMARY KEY, token UUID NOT NULL, expires_at TIMESTAMPTZ NOT NULL
);
CREATE INDEX IF NOT EXISTS fuel_history ON fuel_app.fuel_logs(vehicle_id, filled_on, filled_time);
CREATE INDEX IF NOT EXISTS price_history ON fuel_app.fuel_prices(fuel_type, price_zone, effective_at DESC);
CREATE INDEX IF NOT EXISTS fuel_log_price ON fuel_app.fuel_logs(price_id);
-- This private schema must NOT be added to Supabase's exposed API schemas.
REVOKE ALL ON ALL TABLES IN SCHEMA fuel_app FROM PUBLIC;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA fuel_app FROM PUBLIC;
DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname='anon') THEN
        EXECUTE 'REVOKE ALL ON SCHEMA fuel_app FROM anon';
        EXECUTE 'REVOKE ALL ON ALL TABLES IN SCHEMA fuel_app FROM anon';
    END IF;
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname='authenticated') THEN
        EXECUTE 'REVOKE ALL ON SCHEMA fuel_app FROM authenticated';
        EXECUTE 'REVOKE ALL ON ALL TABLES IN SCHEMA fuel_app FROM authenticated';
    END IF;
END $$;
INSERT INTO fuel_app.schema_migrations(version) VALUES ('001_initial') ON CONFLICT DO NOTHING;
